sudo: required

language: go
before_script:
  - sleep 15
  - mongo --version
go:
  - 1.7
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
